- id: doi:10.1109/MSP.2017.2718040
  type: paper
  tags: DPE
  
- id: doi:10.1109/PLANS53410.2023.10140046
  type: paper
  tags: DPE

- id: doi:10.1109/TAES.2023.3312350
  type: paper
  tags: DPE
  
- id: doi:10.23919/FUSION49751.2022.9841291
  type: paper
  tags: APBM
  
- id: doi:10.1109/ICASSP49357.2023.10095758
  type: paper
  tags: MCRB 
  
- id: doi:10.33012/2024.19799
  publisher: Proceedings of the 37th International Technical Meeting of the Satellite Division of The Institute of Navigation (ION GNSS+ 2024)
  title: Assessment of Direct Position Estimation Performance in Multipath Channels
  authors:
    - Shuo Tang
    - Haoqing Li
    - Pau Closas
  date: '2024-09-20'
  type: paper
  tags: DPE
  link: https://www.ion.org/publications/abstract.cfm?articleID=19799
  
- id: doi:10.33012/2024.19800
  publisher: Proceedings of the 37th International Technical Meeting of the Satellite Division of The Institute of Navigation (ION GNSS+ 2024)
  title: Single Difference Code-Based Technique for Direct Position Estimation
  authors:
    - Shuo Tang
    - Haoqing Li
    - Pau Closas
  date: '2024-09-20'
  type: paper
  tags: DPE
  link: https://www.ion.org/publications/abstract.cfm?articleID=19800
  
- id: doi:10.3390/s24186132
  type: article
  tags: APBM
  
  id: arxiv:2410.12289
  type: magazine
  tags: APBM
